FROM python:3.6.5-alpine

# Install system dependencies
RUN apk update && \
  apk add --virtual build-deps gcc python-dev musl-dev && \
  apk add postgresql-dev && \
  apk add netcat-openbsd

# Change working directory
WORKDIR /usr/src/app

# Install python dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# Add entrypoint
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint.sh
RUN ["chmod", "0755", "/usr/src/app/entrypoint.sh"]

# Copy application
COPY . /usr/src/app

# Run server
CMD ["/usr/src/app/entrypoint.sh"]
